### ISSUE TITLE
A rider should be able to view his/her current request that is open. 

### ISSUE THREAD

**Issue by chanhwi0117** [jlknauer/FastLane#2]
As a rider, I want to be able to view my current requests that I have requested to travel between two locations so that I can cancel a request, to see if the request has been accepted, be able to phone/email drivers, offer more fare, see the driver's profile and rating.

Story Points: 10/10

**Comment by hellosusan** [comment]
US 01.02.01: update
As a rider, I want to be able to view my current requests that content: departure location, the destination location, the date that opened the request and the price of the ride after the offering step.
