### ISSUE TITLE
A rider should be able to view their current request even when offline.

### ISSUE THREAD

**Issue by chanhwi0117** [jlknauer/FastLane#20]
I should be able to view my current request even when offline as their won't be always a internet connection to view valuable information.

Story Point: 8/10

**Comment by jlknauer** [comment]
Will be implementing this featuring using persistent app specific storage.

- [ ] After request is accepted, save request data to file

- [ ] If database download fails, pull request from file

- [ ] Once database connection is re-established and request is finished, purge file cache
